services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: spark_db
      POSTGRES_USER: spark_user_name
      POSTGRES_PASSWORD: spark_my_secret_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./init_db:/docker-entrypoint-initdb.d 
      - ./input_data:/input_data_mount 
    networks:
      - BigDataSpark_network

  spark-master:
    image: bitnamilegacy/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_NO_DAEMONIZE=yes
    ports:
      - "8080:8080" 
      - "7077:7077" 
    volumes:
      - ./spark_apps:/opt/spark-apps
      - ./jars:/opt/spark/jars   
    networks:
      - BigDataSpark_network
    depends_on:
      - postgres

  spark-worker:
    image: bitnamilegacy/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G 
      - SPARK_NO_DAEMONIZE=yes 
    volumes:
      - ./spark_apps:/opt/spark-apps
      - ./jars:/opt/spark/jars
    networks:
      - BigDataSpark_network
    depends_on:
      - spark-master

  clickhouse:
    image: yandex/clickhouse-server:latest 
    container_name: clickhouse_db
    ports:
      - "8123:8123" 
      - "9000:9000" 
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits: 
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - BigDataSpark_network

  mongodb:
    image: mongo:5.0
    container_name: mongodb_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - BigDataSpark_network

volumes:
  postgres_data: 
  clickhouse_data: 
  mongodb_data:

networks:
  BigDataSpark_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16