services:
  postgres:
    image: postgres:16
    container_name: snowflake-postgres
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: pg_db_lab_1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
      - ./csv_data:/csvdata  
      - ./snowflake:/snowflake
    networks:
      - BigDataSnowflake_network

volumes:
  postgres_data:

networks:
  BigDataSnowflake_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
